title: Peter Few # your name (or website title) here
logo: "Flowers Round.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  8 years of experience working within the scientific sector. I have a BSc in Biological Science from the University of the West of England.  
  <br><br>
  Currently looking to improve my data skills and get a job within the data analysis/science sector. I will be showcasing my progress here.   
  <br><br>
  <a href="https://www.linkedin.com/in/peter-few-98424998/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
